// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "new-york": {
    "multistep": {
      name: "multistep",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["src/registry/new-york/ui/multistep.tsx"],
      component: React.lazy(() => import("@/registry/new-york/ui/multistep.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "copy": {
      name: "copy",
      type: "registry:ui",
      registryDependencies: ["tooltip"],
      files: ["src/registry/new-york/ui/copy.tsx"],
      component: React.lazy(() => import("@/registry/new-york/ui/copy.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "button": {
      name: "button",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["src/registry/new-york/ui/button.tsx"],
      component: React.lazy(() => import("@/registry/new-york/ui/button.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "skeleton": {
      name: "skeleton",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["src/registry/new-york/ui/skeleton.tsx"],
      component: React.lazy(() => import("@/registry/new-york/ui/skeleton.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "tooltip": {
      name: "tooltip",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["src/registry/new-york/ui/tooltip.tsx"],
      component: React.lazy(() => import("@/registry/new-york/ui/tooltip.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "connect-wallet": {
      name: "connect-wallet",
      type: "registry:block",
      registryDependencies: ["about-wallets","connect-icons","select-wallet","select-account"],
      files: ["src/registry/new-york/block/connect-wallet.tsx"],
      component: React.lazy(() => import("@/registry/new-york/block/connect-wallet.tsx")),
      source: "src/__registry__/new-york/block/connect-wallet.tsx",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "about-wallets": {
      name: "about-wallets",
      type: "registry:block",
      registryDependencies: ["button"],
      files: ["src/registry/new-york/block/about-wallets.tsx"],
      component: React.lazy(() => import("@/registry/new-york/block/about-wallets.tsx")),
      source: "src/__registry__/new-york/block/about-wallets.tsx",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "select-account": {
      name: "select-account",
      type: "registry:block",
      registryDependencies: ["button","copy","skeleton","connect-icons"],
      files: ["src/registry/new-york/block/select-account.tsx"],
      component: React.lazy(() => import("@/registry/new-york/block/select-account.tsx")),
      source: "src/__registry__/new-york/block/select-account.tsx",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "select-wallet": {
      name: "select-wallet",
      type: "registry:block",
      registryDependencies: ["button","skeleton","connect-icons"],
      files: ["src/registry/new-york/block/select-wallet.tsx"],
      component: React.lazy(() => import("@/registry/new-york/block/select-wallet.tsx")),
      source: "src/__registry__/new-york/block/select-wallet.tsx",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "connect-icons": {
      name: "connect-icons",
      type: "registry:block",
      registryDependencies: undefined,
      files: ["src/registry/new-york/block/connect-icons.tsx"],
      component: React.lazy(() => import("@/registry/new-york/block/connect-icons.tsx")),
      source: "src/__registry__/new-york/block/connect-icons.tsx",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
  },  "default": {
    "multistep": {
      name: "multistep",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["src/registry/default/ui/multistep.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/multistep.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "copy": {
      name: "copy",
      type: "registry:ui",
      registryDependencies: ["tooltip"],
      files: ["src/registry/default/ui/copy.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/copy.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "button": {
      name: "button",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["src/registry/default/ui/button.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/button.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "skeleton": {
      name: "skeleton",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["src/registry/default/ui/skeleton.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/skeleton.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "tooltip": {
      name: "tooltip",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["src/registry/default/ui/tooltip.tsx"],
      component: React.lazy(() => import("@/registry/default/ui/tooltip.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "connect-wallet": {
      name: "connect-wallet",
      type: "registry:block",
      registryDependencies: ["about-wallets","connect-icons","select-wallet","select-account"],
      files: ["src/registry/default/block/connect-wallet.tsx"],
      component: React.lazy(() => import("@/registry/default/block/connect-wallet.tsx")),
      source: "src/__registry__/default/block/connect-wallet.tsx",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "about-wallets": {
      name: "about-wallets",
      type: "registry:block",
      registryDependencies: ["button"],
      files: ["src/registry/default/block/about-wallets.tsx"],
      component: React.lazy(() => import("@/registry/default/block/about-wallets.tsx")),
      source: "src/__registry__/default/block/about-wallets.tsx",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "select-account": {
      name: "select-account",
      type: "registry:block",
      registryDependencies: ["button","copy","skeleton","connect-icons"],
      files: ["src/registry/default/block/select-account.tsx"],
      component: React.lazy(() => import("@/registry/default/block/select-account.tsx")),
      source: "src/__registry__/default/block/select-account.tsx",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "select-wallet": {
      name: "select-wallet",
      type: "registry:block",
      registryDependencies: ["button","skeleton","connect-icons"],
      files: ["src/registry/default/block/select-wallet.tsx"],
      component: React.lazy(() => import("@/registry/default/block/select-wallet.tsx")),
      source: "src/__registry__/default/block/select-wallet.tsx",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "connect-icons": {
      name: "connect-icons",
      type: "registry:block",
      registryDependencies: undefined,
      files: ["src/registry/default/block/connect-icons.tsx"],
      component: React.lazy(() => import("@/registry/default/block/connect-icons.tsx")),
      source: "src/__registry__/default/block/connect-icons.tsx",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
  },
}
